---
services:
    backend:
        container_name: eeva-backend
        pull_policy: build
        build:
            context: ..
            dockerfile: docker/backend.dockerfile
        image: eeva-backend
        volumes:
            - ../${PROMPT_DIR?prompt dir}:/prompts/
            - ../${DATA_PATH?data_path}:/data/
        ports:
            - 8000:8000

networks:
    app-network:
        driver: bridge
