defaults:
  - override hydra/job_logging: custom
  - _self_

hydra:
  run:
    dir: ./output/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

data_dir: "data"
secrets_path: "secrets.json"

model: "gpt-5-nano:openai"
reasoning_effort: "minimal"
identity_prompt_path: "identity"
identity_extraction_prompt_path: "identity_extraction"
explicit_cot: true

num_tests: 3

exclude_questions: []
include_questions: null

exclude_users: []
include_users: null
only_couples: false
answer_progress_minimum: 0.0
num_answers_minimum: 1
