defaults:
  - override hydra/job_logging: custom
  - _self_

hydra:
  run:
    dir: ./output/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

data_dir: "data"
secrets_path: "secrets.json"

exclude_questions: []
include_questions: null

exclude_users: []
include_users: null
answer_progress_minimum: 0.0
num_answers_minimum: 1
