defaults:
  - override hydra/job_logging: custom
  - _self_

hydra:
  run:
    dir: ./output/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}

data_dir: "data"
prompts_dir: "prompts"
secrets_path: "secrets.json"

model: "gpt-5-nano:openai"
reasoning_effort: "minimal"
identity_prompt_path: "identity"
identity_extraction_prompt_path: "identity_extraction"
explicit_cot: true
system_prompt_path: "default_system_message"

num_tests: 3

question_exclusion_sets: []
question_inclusion_sets: null

user_exclusion_sets:
  - default_exclude
user_inclusion_sets: null
only_couples: false
answer_progress_minimum: 0.0
num_answers_minimum: 1
