defaults:
  - default
  - _self_

secrets_path: "secrets.json"
data_dir: "data"

model: "gpt-5-nano:openai"
reasoning_effort: "minimal"
identity_prompt_path: "identity"
identity_extraction_prompt_path: "identity_extraction"
explicit_cot: true

num_tests: 3
