# Configures logging for your application code (the "job").
version: 1

disable_existing_loggers: false

formatters:
  standard:
    format: "%(asctime)s | %(levelname)-8s | %(name)s:%(lineno)d | %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout

  debug_file:
    class: logging.FileHandler
    level: DEBUG
    formatter: standard
    filename: ${hydra.run.dir}/debug.log
    mode: a

  info_file:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: ${hydra.run.dir}/info.log
    mode: a

loggers:
  # Completely silence httpx and its transport (httpcore)
  httpx:
    level: DEBUG
    handlers: [debug_file]
    propagate: false

  httpcore:
    level: DEBUG
    handlers: [debug_file]
    propagate: false

root:
  level: DEBUG
  handlers: [console, debug_file, info_file]
